package presentation;

import domain.*;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

public class GUIRoomBook extends javax.swing.JFrame {

    /**
     * Creates new form GUIRoomBook
     */
    Control con = new Control();
    Customer k;
    Booking bo;
    ArrayList b;
    ArrayList ka;
    ArrayList id;
    ArrayList r;
    DefaultListModel dflCreate = new DefaultListModel();
    DefaultListModel dflBooking = new DefaultListModel();
    DefaultListModel dflRooms = new DefaultListModel();

    public GUIRoomBook() {
        initComponents();
        jListRooms.setModel(dflRooms);
        jListBooking.setModel(dflBooking);
        jListCreate.setModel(dflCreate);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Fnamefield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Snamefield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Addressfield = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Countryfield = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Phonefield = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Emailfield = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Arrival = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Depature = new javax.swing.JTextField();
        Travelagencycombobox = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Bookbutton = new javax.swing.JButton();
        Undobutton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Noofguestfield = new javax.swing.JTextField();
        Statuslabeldontchange = new javax.swing.JLabel();
        Clearfieldsbutton = new javax.swing.JButton();
        Statuslabel = new javax.swing.JLabel();
        jButtonAddCustomer = new javax.swing.JButton();
        jButtongetCustomer = new javax.swing.JButton();
        jTextFieldgetLastName = new javax.swing.JTextField();
        jTextFieldCustomerID = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListCreate = new javax.swing.JList();
        jButtonResetCustomer = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jTextFieldgetcustomerID = new javax.swing.JTextField();
        jButtonSearchCustomerID = new javax.swing.JButton();
        jTextFieldRoomNo = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jCheckBoxPaid = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldgetArrival = new javax.swing.JTextField();
        jTextFieldgetDepature = new javax.swing.JTextField();
        jButtongetArrivals = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListBooking = new javax.swing.JList();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextFieldresNo = new javax.swing.JTextField();
        jbuttonGetArrivalsFromResNo = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jButtonEditBooking = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        departureEditField = new javax.swing.JTextField();
        noOfGuestsEditField = new javax.swing.JTextField();
        arrivalEditField = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jButtonDelete = new javax.swing.JButton();
        jCheckBoxPaidBooking = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jTextFieldcheckRoomArrival = new javax.swing.JTextField();
        jTextFieldcheckRoomDeparture = new javax.swing.JTextField();
        jButtonCheckRooms = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListRooms = new javax.swing.JList();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Forename");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 33, -1, -1));

        Fnamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FnamefieldActionPerformed(evt);
            }
        });
        jPanel1.add(Fnamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 53, 86, -1));

        jLabel2.setText("Last name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 33, -1, -1));
        jPanel1.add(Snamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 53, 86, -1));

        jLabel3.setText("Address");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 33, -1, -1));

        Addressfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressfieldActionPerformed(evt);
            }
        });
        jPanel1.add(Addressfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 53, 86, -1));

        jLabel4.setText("Country");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 89, -1, -1));
        jPanel1.add(Countryfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 115, 86, -1));

        jLabel5.setText("Phone");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 89, -1, -1));

        Phonefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhonefieldActionPerformed(evt);
            }
        });
        jPanel1.add(Phonefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 115, 86, -1));

        jLabel6.setText("Email");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 89, -1, -1));

        Emailfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailfieldActionPerformed(evt);
            }
        });
        jPanel1.add(Emailfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 115, 86, -1));

        jLabel7.setText("Arrival date");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 536, -1, -1));
        jPanel1.add(Arrival, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 561, 90, -1));

        jLabel8.setText("Travel Agency");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 427, -1, -1));
        jPanel1.add(Depature, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 561, 90, -1));

        Travelagencycombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "BestTravel", "AwesomeAdventure", "DeluxeVacation", "Sun&Spa Agency" }));
        jPanel1.add(Travelagencycombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 502, 82, -1));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 561, -1, -1));

        jLabel10.setText("Departure date");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 536, -1, -1));

        Bookbutton.setText("Book");
        Bookbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Bookbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 598, 86, -1));

        Undobutton.setText("Undo Book");
        jPanel1.add(Undobutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 598, -1, -1));

        jLabel11.setText("Room Type");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 427, -1, -1));

        jLabel12.setText("No. of Guests");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 531, -1, 24));
        jPanel1.add(Noofguestfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 561, 66, -1));

        Statuslabeldontchange.setText("Status:");
        jPanel1.add(Statuslabeldontchange, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 622, -1, -1));

        Clearfieldsbutton.setText("Clear Fields");
        Clearfieldsbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearfieldsbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Clearfieldsbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 598, -1, -1));
        jPanel1.add(Statuslabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 622, 466, 14));

        jButtonAddCustomer.setText("Add Customer");
        jButtonAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddCustomerActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAddCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, -1));

        jButtongetCustomer.setText("Search Last Name");
        jButtongetCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtongetCustomerActionPerformed(evt);
            }
        });
        jPanel1.add(jButtongetCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 299, 140, -1));
        jPanel1.add(jTextFieldgetLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 302, 132, -1));
        jPanel1.add(jTextFieldCustomerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 561, 60, -1));

        jLabel13.setText("Customer ID");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 536, -1, -1));

        jLabel14.setText("Enter last name");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 304, -1, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 411, 401, 10));

        jScrollPane1.setViewportView(jListCreate);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 151, 401, 107));

        jButtonResetCustomer.setText("Clear field");
        jButtonResetCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetCustomerActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonResetCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 376, 140, -1));

        jLabel24.setText("Enter CustomerID");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 272, -1, -1));

        jTextFieldgetcustomerID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldgetcustomerIDActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldgetcustomerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 270, 132, -1));

        jButtonSearchCustomerID.setText("Search Customer ID");
        jButtonSearchCustomerID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchCustomerIDActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSearchCustomerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 270, -1, -1));
        jPanel1.add(jTextFieldRoomNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, 60, -1));

        jLabel31.setText("Room Number");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, -1, -1));

        jCheckBoxPaid.setText("Paid");
        jPanel1.add(jCheckBoxPaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 600, -1, -1));

        jTabbedPane1.addTab("Create", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldgetArrival.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldgetArrivalActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldgetArrival, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 39, 80, -1));
        jPanel2.add(jTextFieldgetDepature, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 39, 80, -1));

        jButtongetArrivals.setText("Get Arrivals");
        jButtongetArrivals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtongetArrivalsActionPerformed(evt);
            }
        });
        jPanel2.add(jButtongetArrivals, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 36, -1, -1));

        jLabel15.setText("Arrival");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 16, -1, -1));

        jLabel16.setText("Depature");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 16, -1, -1));

        jScrollPane2.setViewportView(jListBooking);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 133, 669, 184));

        jLabel17.setText("Arrival");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 113, 48, -1));

        jLabel18.setText("Departure");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 113, 57, -1));

        jLabel19.setText("Customer ID");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 76, -1));

        jLabel20.setText("Payment");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        jLabel21.setText("Room no.");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, -1));

        jLabel22.setText("Guests");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 113, 41, -1));

        jLabel23.setText("Res no.");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 45, -1));
        jPanel2.add(jTextFieldresNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 62, -1));

        jbuttonGetArrivalsFromResNo.setText("Get Arrivals");
        jbuttonGetArrivalsFromResNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonGetArrivalsFromResNoActionPerformed(evt);
            }
        });
        jPanel2.add(jbuttonGetArrivalsFromResNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 36, -1, -1));

        jLabel27.setText("Res no.");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, -1));

        jButtonEditBooking.setText("Change Arrival");
        jButtonEditBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditBookingActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonEditBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, -1, -1));

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        jPanel2.add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, -1, -1));
        jPanel2.add(departureEditField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 87, -1));
        jPanel2.add(noOfGuestsEditField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 87, -1));
        jPanel2.add(arrivalEditField, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 373, 87, -1));

        jLabel28.setText("Arrival");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 338, -1, -1));

        jLabel29.setText("Departure");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, -1, -1));

        jLabel30.setText("No of Guests");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, -1, -1));

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, -1, -1));

        jCheckBoxPaidBooking.setText("Paid");
        jPanel2.add(jCheckBoxPaidBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, -1, -1));

        jTabbedPane1.addTab("Booking list", jPanel2);

        jTextFieldcheckRoomDeparture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldcheckRoomDepartureActionPerformed(evt);
            }
        });

        jButtonCheckRooms.setText("Check Rooms");
        jButtonCheckRooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheckRoomsActionPerformed(evt);
            }
        });

        jLabel25.setText("Arrival");

        jLabel26.setText("Departue");

        jScrollPane3.setViewportView(jListRooms);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jTextFieldcheckRoomArrival, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jTextFieldcheckRoomDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCheckRooms, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(396, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldcheckRoomArrival, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldcheckRoomDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCheckRooms))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(412, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Room list", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 681, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 655, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Sport", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtongetCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtongetCustomerActionPerformed
        String lname = jTextFieldgetLastName.getText();

        ka = con.getCustomer(lname);
        //String s = String.valueOf(k.getCustomerID());
        //jTextFieldCustomerID.setText(s);
        if (ka != null) {
            for (int i = 0; i < ka.size(); i++) {
                dflCreate.addElement(ka.get(i).toString());
            }

        } else {
            Statuslabel.setText("Could not get Customer");

        }
        con.resetCustomer();
        jTextFieldgetLastName.setText("");
    }//GEN-LAST:event_jButtongetCustomerActionPerformed

    private void jButtonAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddCustomerActionPerformed
        con.createNewCustomer(Fnamefield.getText(), Snamefield.getText(), Countryfield.getText(), Emailfield.getText(), Integer.parseInt(Phonefield.getText()), Addressfield.getText());

        boolean status = con.saveCustomer();
        if (status) {
            Statuslabel.setText("Customer saved");
        } else {
            Statuslabel.setText("Customer could not be saved!");
        }
    }//GEN-LAST:event_jButtonAddCustomerActionPerformed

    private void ClearfieldsbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearfieldsbuttonActionPerformed
        Fnamefield.setText("");
        Snamefield.setText("");
        Arrival.setText("");
        Addressfield.setText("");
        Countryfield.setText("");
        Depature.setText("");
        Phonefield.setText("");
        Emailfield.setText("");
        Noofguestfield.setText("");
        Statuslabel.setText("");
        jTextFieldCustomerID.setText("");
        jTextFieldgetLastName.setText("");

        con.resetBooking();
    }//GEN-LAST:event_ClearfieldsbuttonActionPerformed

    private void BookbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookbuttonActionPerformed
        //comment
        int CustomerID = Integer.parseInt(jTextFieldCustomerID.getText());
        int paid = 0;
        if (jCheckBoxPaid.isSelected() == true) {
            paid = 1;
        }

        con.createNewBooking(Arrival.getText(), Depature.getText(), Integer.parseInt(Noofguestfield.getText()), paid, Integer.parseInt(jTextFieldRoomNo.getText()), CustomerID);
        boolean status = con.saveBooking();
        if (status) {
            Statuslabel.setText("Booking saved");
        } else {
            Statuslabel.setText("Booking could not be saved");
        }

        con.resetBooking();
    }//GEN-LAST:event_BookbuttonActionPerformed

    private void EmailfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailfieldActionPerformed

    private void PhonefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhonefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhonefieldActionPerformed

    private void AddressfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressfieldActionPerformed

    private void FnamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FnamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FnamefieldActionPerformed

    private void jButtongetArrivalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtongetArrivalsActionPerformed
        String arrival = jTextFieldgetArrival.getText();
        String departure = jTextFieldgetDepature.getText();

        b = con.getBookingList(arrival, departure);
        if (b != null) {
            for (int i = 0; i < b.size(); i++) {

                dflBooking.addElement(b.get(i).toString());

            }

        } else {
            Statuslabel.setText("Could not get Customer");
        }
        con.resetBooking();

    }//GEN-LAST:event_jButtongetArrivalsActionPerformed

    private void jButtonResetCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetCustomerActionPerformed
        if (evt.getSource() == jButtonResetCustomer) {
            DefaultListModel listModel = (DefaultListModel) jListCreate.getModel();
            listModel.removeAllElements();
        }
    }//GEN-LAST:event_jButtonResetCustomerActionPerformed

    private void jTextFieldgetcustomerIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldgetcustomerIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldgetcustomerIDActionPerformed

    private void jButtonSearchCustomerIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchCustomerIDActionPerformed
        String customerID = jTextFieldgetcustomerID.getText();

        id = con.getCustomerID(customerID);
        //String s = String.valueOf(k.getCustomerID());
        //jTextFieldCustomerID.setText(s);
        if (id != null) {
            for (int i = 0; i < id.size(); i++) {
                dflCreate.addElement(id.get(i).toString());
            }
        } else {
            Statuslabel.setText("Could not get Customer");

        }
        con.resetCustomer();
        jTextFieldgetcustomerID.setText("");
    }//GEN-LAST:event_jButtonSearchCustomerIDActionPerformed

    private void jButtonCheckRoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheckRoomsActionPerformed
        String arrival = jTextFieldcheckRoomArrival.getText();
        String departure = jTextFieldcheckRoomDeparture.getText();
        r = con.getRoomsList(arrival, departure);
        if (r != null) {
            for (int i = 0; i < r.size(); i++) {
                dflRooms.addElement(r.get(i).toString());

            }

        } else {
            Statuslabel.setText("Could not get Rooms");
        }
        con.resetRooms();
    }//GEN-LAST:event_jButtonCheckRoomsActionPerformed

    private void jTextFieldcheckRoomDepartureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldcheckRoomDepartureActionPerformed

    }//GEN-LAST:event_jTextFieldcheckRoomDepartureActionPerformed

    private void jButtonEditBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditBookingActionPerformed

        Object booking = jListBooking.getSelectedValue();
        arrivalEditField.setText(booking.toString().substring(0, 10));
        departureEditField.setText(booking.toString().substring(20, 30));
        noOfGuestsEditField.setText(booking.toString().substring(40, 41));
    }//GEN-LAST:event_jButtonEditBookingActionPerformed

    private void jbuttonGetArrivalsFromResNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonGetArrivalsFromResNoActionPerformed

        int resno = Integer.parseInt(jTextFieldresNo.getText());
        Booking arrival = con.findResNumber(resno);
        if (arrival != null) {

            dflBooking.addElement(arrival);
        }
//        con.resetBooking();
    }//GEN-LAST:event_jbuttonGetArrivalsFromResNoActionPerformed

    private void jTextFieldgetArrivalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldgetArrivalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldgetArrivalActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed

        String arrival = arrivalEditField.getText();
        String departure = departureEditField.getText();
        int numberOfGuests = Integer.parseInt(noOfGuestsEditField.getText());
        int paid = 0;
        if (jCheckBoxPaidBooking.isSelected() == true) {
            paid = 1;
        }
        bo = con.changeBookingInformation(arrival, departure, numberOfGuests, paid);
        boolean status = con.saveBooking();

    }//GEN-LAST:event_updateButtonActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        con.deleteBooking();
        boolean status = con.saveBooking();
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIRoomBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIRoomBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIRoomBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIRoomBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIRoomBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Addressfield;
    private javax.swing.JTextField Arrival;
    private javax.swing.JButton Bookbutton;
    private javax.swing.JButton Clearfieldsbutton;
    private javax.swing.JTextField Countryfield;
    private javax.swing.JTextField Depature;
    private javax.swing.JTextField Emailfield;
    private javax.swing.JTextField Fnamefield;
    private javax.swing.JTextField Noofguestfield;
    private javax.swing.JTextField Phonefield;
    private javax.swing.JTextField Snamefield;
    private javax.swing.JLabel Statuslabel;
    private javax.swing.JLabel Statuslabeldontchange;
    private javax.swing.JComboBox Travelagencycombobox;
    private javax.swing.JButton Undobutton;
    private javax.swing.JTextField arrivalEditField;
    private javax.swing.JTextField departureEditField;
    private javax.swing.JButton jButtonAddCustomer;
    private javax.swing.JButton jButtonCheckRooms;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonEditBooking;
    private javax.swing.JButton jButtonResetCustomer;
    private javax.swing.JButton jButtonSearchCustomerID;
    private javax.swing.JButton jButtongetArrivals;
    private javax.swing.JButton jButtongetCustomer;
    private javax.swing.JCheckBox jCheckBoxPaid;
    private javax.swing.JCheckBox jCheckBoxPaidBooking;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jListBooking;
    private javax.swing.JList jListCreate;
    private javax.swing.JList jListRooms;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldCustomerID;
    private javax.swing.JTextField jTextFieldRoomNo;
    private javax.swing.JTextField jTextFieldcheckRoomArrival;
    private javax.swing.JTextField jTextFieldcheckRoomDeparture;
    private javax.swing.JTextField jTextFieldgetArrival;
    private javax.swing.JTextField jTextFieldgetDepature;
    private javax.swing.JTextField jTextFieldgetLastName;
    private javax.swing.JTextField jTextFieldgetcustomerID;
    private javax.swing.JTextField jTextFieldresNo;
    private javax.swing.JButton jbuttonGetArrivalsFromResNo;
    private javax.swing.JTextField noOfGuestsEditField;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
